server {
    listen 80;
    server_name payment.dev-monty.me;

    resolver 127.0.0.11 valid=30s;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;

    # Payment Frontend
    location / {
        proxy_pass http://frontend-payment:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /healthcheck {
        default_type text/plain;
        return 200 "OK\n";
    }
}