name: pull-request-master.yml
on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_master:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v5

      # 시크릿 스토어 체크아웃
      - name: Check out Secrets store
        uses: actions/checkout@v5
        with:
          repository: 'dev-montyoh/secrets-store'
          token: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}
          path: secrets-store

      # 시크릿 값들 로드
      - name: Load secrets
        run: |
          echo "Loading shared secrets..."
          export $(grep -v '^#' secrets-store/github.properties | xargs)
          echo "Secrets loaded!"

      # Github Registry 로그인
      - name: Log in to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ env.DOCKER_REGISTRY_ACCESS_TOKEN }}

      # Docker Image Build
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-proxy-server:latest \
          -t ghcr.io/${{ github.repository_owner }}/backend-proxy-server:${{ github.run_number }} .

      # Docker Push
      - name: Deploy proxy server
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-proxy-server:latest
          docker push ghcr.io/${{ github.repository_owner }}/backend-proxy-server:${{ github.run_number }}