name: push-master.yml
on:
  push:
    branches:
      - master

jobs:
  push_master:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v5

      # SSH 연결
      - name: Set up SSH
        uses: appleboy/ssh-action@v1
        env:
          DOCKER_REGISTRY_ACCESS_TOKEN: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
          DOCKER_REGISTRY_USERNAME: ${{ github.repository_owner }}
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKER_REGISTRY_ACCESS_TOKEN,DOCKER_REGISTRY_USERNAME
          script: |
            # 기존 서비스 및 이미지 삭제
            docker ps -q --filter "name=backend-proxy-server" | xargs -r docker stop
            docker ps -a -q --filter "name=backend-proxy-server" | xargs -r docker rm
            docker images -q ghcr.io/$DOCKER_REGISTRY_USERNAME/backend-proxy-server:latest | xargs -r docker rmi -f
            
            # docker-compose.yml 연결 및 특정 서비스 시작
            cd /home/ec2-user/app
            curl -L -o docker-compose.yml https://raw.githubusercontent.com/dev-montyoh/iac-terraform/refs/heads/master/docker-compose.yml
            docker-compose pull backend-proxy-server
            docker-compose up -d backend-proxy-server